### ISSUE TITLE
Fix video links from http:// to https:// 

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-user-docs#1]
We have several embedded videos in the flymine docs, present here: https://flymine.readthedocs.io/en/latest/videos/Documentationvideos.html

The code for these videos is here: https://github.com/intermine/intermine-user-docs/blob/master/videos/Documentationvideos.txt 

The videos are not loading due to a fixable security risk - the docs page for the videos is on `https`, and the links to the videos all start with `http`.

To fix this, change the links to the videos in the code to start with https instead. 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by calvin-puram** [comment]
I will love to work on this task

**Comment by yochannah** [comment]
Hey Calvin - go ahead! Let us know if you have any questions at all :)

**Comment by Ruben80** [comment]
Can I help in this project?

**Comment by yochannah** [comment]
Hey @Ruben80 ! Apologies, this issue was solved yesterday but didn't get closed - thanks for offering though! If you're interested there are some issues at http://intermine.org/contributing/ - they're mostly not first-timer issues though.

**Comment by Ruben80** [comment]
Hi, do you know some beginner issue repos?

Op wo 19 feb. 2020 21:37 schreef Yo Yehudi <notifications@github.com>:
