### ISSUE TITLE
Image on MyMine not showing

### ISSUE THREAD

**Issue by Ruth-ikegah** [intermine/intermine-user-docs#12]
## Description
While studying the  User documentation, I noticed that the first annotated image for MyMine is not showing as shown in the screenshot below.

![MyMine-—-InterMine-User-1-0-documentation](https://user-images.githubusercontent.com/62059002/96356291-428c2200-10e4-11eb-9717-d63735eff7bf.png)

Please I will love to solve this issue, although I have a question. Going through the image file formats, I noticed the file extensions are not consistent, some having .png, .tiff, and .odg. I will love to know why just one file extension was not used. Thanks.

**Comment by aditisingh2412** [comment]
Hey, I'm a newbie. Is this issue still open? Can I work on this issue?

**Comment by ajayaallen** [comment]
Hey, Can I work on this issue?

**Comment by uosl** [comment]
Hello! The documentation has been completely redone since this issue was created, so this is no longer necessary. Thanks for showing interest!
