### ISSUE TITLE
Remove "Module Index" link

### ISSUE THREAD

**Issue by fequerver** [intermine/intermine-user-docs#4]
It's broken and supposed to be used for python modules.
It serve no use to Intermine user documentation.

location: https://flymine.readthedocs.io/en/latest/#indices-and-tables
page: https://flymine.readthedocs.io/en/latest/py-modindex.html

**Comment by AishaSaman** [comment]
Can I resolve this issue ?

**Comment by uosl** [comment]
Sorry @AishaSaman, this was already fixed with an older PR #5. Thank you for looking into this though!
