### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fequerver** [intermine/intermine-user-docs#6]
Text: "Are my interacting genes/proteins are expressed in the same tissue/dev stage?"

Link: https://flymine.readthedocs.io/en/latest/cookbook/interactions/cookbookinteractions.html#are-my-interacting-genes-proteins-are-expressed-in-the-same-tissue-dev-stage

I didn't understand exactly what should be the question, so I'm just filling the issue.

**Comment by Ruth-ikegah** [comment]
Hi, I am an Outreachy applicant. I have linked a PR to solve this issue. Thanks!
